set (dpdk_base_path "/home/pawel/Programming/dpdk/dpdk-16.07")
if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
    set (dpdk_arch "x86_64-native-linuxapp-gcc")
elseif (${CMAKE_CXX_COMPILER_ID} STREQUAL "Clang")
    set (dpdk_arch "x86_64-native-linuxapp-clang")
endif ()
set (dpdk_path "${dpdk_base_path}/${dpdk_arch}")

set (include_dir "${dpdk_path}/include")
if (EXISTS ${include_dir} AND IS_DIRECTORY ${include_dir})
    set (DPDK_INCLUDE_DIR ${include_dir})
    message (STATUS "dpdk include dir: " ${DPDK_INCLUDE_DIR})
    if (EXISTS "${include_dir}/rte_config.h")
        set (DPDK_INCLUDE_CONFIG "-include ${include_dir}/rte_config.h")
        message (STATUS "dpdk include config: " ${DPDK_INCLUDE_CONFIG})
    endif ()
endif ()

set (lib_dir "${dpdk_path}/lib")
if (EXISTS ${lib_dir} AND IS_DIRECTORY ${lib_dir})
    set (DPDK_LIBRARY_DIR ${lib_dir})
    set (DPDK_LIBRARIES "-Wl,--no-as-needed -Wl,--whole-archive -lrte_mbuf -lrte_eal -lrte_mempool -lrte_ring -lethdev -lrte_pmd_ixgbe -lrte_pmd_pcap -lrte_kvargs -Wl,--no-whole-archive")
    message (STATUS "dpdk library dir: " ${DPDK_LIBRARY_DIR})
    message (STATUS "dpdk libraries: " ${DPDK_LIBRARIES})
endif ()

include (FindPackageHandleStandardArgs)
find_package_handle_standard_args ("dpdk" DEFAULT_MSG DPDK_INCLUDE_DIR DPDK_INCLUDE_CONFIG DPDK_LIBRARY_DIR DPDK_LIBRARIES)

mark_as_advanced (DPDK_INCLUDE_DIR DPDK_INCLUDE_CONFIG DPDK_LIBRARY_DIR DPDK_LIBRARIES)
